version: 2.1
#
orbs:
  win: circleci/windows@2.4.0

workflows:
  hello-world:
    jobs:
      - build
  integration-tests:
    jobs:
      - browser-tests
      - ui-tests

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\HelloWorld
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
      - run:
          name: "Install project dependencies"
          command: .\start.bat
      - save_cache:
          paths:
            - C:\Users\circleci\project\HelloWorld\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
      - run:
          name: "Run Build step"
          command: .\hash.exe -h
      - run:
          name: "Test the executable"
          command: .\start.bat
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe


  browser-tests:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Run browser tests
          command: |
              cd WebBrowserTestsSample/tests/WebBrowserTests
              dotnet test

  ui-tests:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: choco install winappdriver
      - run: 
          name: Run winappdriver in background
          background: true
          command: | 
              .\start.bat
      - run:
          name: Restore and build
          command: |
            .\start.bat
      - run: 
          name: Run UI tests
          command: |
              .\start.bat
 
